/* ==========================================================================
   TÜRKİYE İL / İLÇE LİSTESİ
   --------------------------------------------------------------------------
   81 il ve 973 ilçe. Kaynak: turkiyeapi.dev (açık veri API'si).
   Bu liste Türkiye'nin resmî idari bölümlemesinden alınmıştır; lise taban puanı
   İÇERMEZ. Lise kayıtları ayrı dosyada tutulur (veri/liseler.js).
   ========================================================================== */

const IL_ILCE = [
  {
    il: "Adana",
    kod: 1,
    bolge: "Akdeniz",
    ilceler: [
      "Aladağ",
      "Ceyhan",
      "Çukurova",
      "Feke",
      "İmamoğlu",
      "Karaisalı",
      "Karataş",
      "Kozan",
      "Pozantı",
      "Saimbeyli",
      "Sarıçam",
      "Seyhan",
      "Tufanbeyli",
      "Yumurtalık",
      "Yüreğir"
    ],
  },
  {
    il: "Adıyaman",
    kod: 2,
    bolge: "Güneydoğu Anadolu",
    ilceler: [
      "Besni",
      "Çelikhan",
      "Gerger",
      "Gölbaşı",
      "Kahta",
      "Merkez",
      "Samsat",
      "Sincik",
      "Tut"
    ],
  },
  {
    il: "Afyonkarahisar",
    kod: 3,
    bolge: "Ege",
    ilceler: [
      "Başmakçı",
      "Bayat",
      "Bolvadin",
      "Çay",
      "Çobanlar",
      "Dazkırı",
      "Dinar",
      "Emirdağ",
      "Evciler",
      "Hocalar",
      "İhsaniye",
      "İscehisar",
      "Kızılören",
      "Merkez",
      "Sandıklı",
      "Sinanpaşa",
      "Sultandağı",
      "Şuhut"
    ],
  },
  {
    il: "Ağrı",
    kod: 4,
    bolge: "Doğu Anadolu",
    ilceler: [
      "Diyadin",
      "Doğubayazıt",
      "Eleşkirt",
      "Hamur",
      "Merkez",
      "Patnos",
      "Taşlıçay",
      "Tutak"
    ],
  },
  {
    il: "Amasya",
    kod: 5,
    bolge: "Karadeniz",
    ilceler: [
      "Göynücek",
      "Gümüşhacıköy",
      "Hamamözü",
      "Merkez",
      "Merzifon",
      "Suluova",
      "Taşova"
    ],
  },
  {
    il: "Ankara",
    kod: 6,
    bolge: "İç Anadolu",
    ilceler: [
      "Akyurt",
      "Altındağ",
      "Ayaş",
      "Bala",
      "Beypazarı",
      "Çamlıdere",
      "Çankaya",
      "Çubuk",
      "Elmadağ",
      "Etimesgut",
      "Evren",
      "Gölbaşı",
      "Güdül",
      "Haymana",
      "Kahramankazan",
      "Kalecik",
      "Keçiören",
      "Kızılcahamam",
      "Mamak",
      "Nallıhan",
      "Polatlı",
      "Pursaklar",
      "Sincan",
      "Şereflikoçhisar",
      "Yenimahalle"
    ],
  },
  {
    il: "Antalya",
    kod: 7,
    bolge: "Akdeniz",
    ilceler: [
      "Akseki",
      "Aksu",
      "Alanya",
      "Demre",
      "Döşemealtı",
      "Elmalı",
      "Finike",
      "Gazipaşa",
      "Gündoğmuş",
      "İbradı",
      "Kaş",
      "Kemer",
      "Kepez",
      "Konyaaltı",
      "Korkuteli",
      "Kumluca",
      "Manavgat",
      "Muratpaşa",
      "Serik"
    ],
  },
  {
    il: "Artvin",
    kod: 8,
    bolge: "Karadeniz",
    ilceler: [
      "Ardanuç",
      "Arhavi",
      "Borçka",
      "Hopa",
      "Kemalpaşa",
      "Merkez",
      "Murgul",
      "Şavşat",
      "Yusufeli"
    ],
  },
  {
    il: "Aydın",
    kod: 9,
    bolge: "Ege",
    ilceler: [
      "Bozdoğan",
      "Buharkent",
      "Çine",
      "Didim",
      "Efeler",
      "Germencik",
      "İncirliova",
      "Karacasu",
      "Karpuzlu",
      "Koçarlı",
      "Köşk",
      "Kuşadası",
      "Kuyucak",
      "Nazilli",
      "Söke",
      "Sultanhisar",
      "Yenipazar"
    ],
  },
  {
    il: "Balıkesir",
    kod: 10,
    bolge: "Marmara",
    ilceler: [
      "Altıeylül",
      "Ayvalık",
      "Balya",
      "Bandırma",
      "Bigadiç",
      "Burhaniye",
      "Dursunbey",
      "Edremit",
      "Erdek",
      "Gömeç",
      "Gönen",
      "Havran",
      "İvrindi",
      "Karesi",
      "Kepsut",
      "Manyas",
      "Marmara",
      "Savaştepe",
      "Sındırgı",
      "Susurluk"
    ],
  },
  {
    il: "Bilecik",
    kod: 11,
    bolge: "Marmara",
    ilceler: [
      "Bozüyük",
      "Gölpazarı",
      "İnhisar",
      "Merkez",
      "Osmaneli",
      "Pazaryeri",
      "Söğüt",
      "Yenipazar"
    ],
  },
  {
    il: "Bingöl",
    kod: 12,
    bolge: "Doğu Anadolu",
    ilceler: [
      "Adaklı",
      "Genç",
      "Karlıova",
      "Kiğı",
      "Merkez",
      "Solhan",
      "Yayladere",
      "Yedisu"
    ],
  },
  {
    il: "Bitlis",
    kod: 13,
    bolge: "Doğu Anadolu",
    ilceler: [
      "Adilcevaz",
      "Ahlat",
      "Güroymak",
      "Hizan",
      "Merkez",
      "Mutki",
      "Tatvan"
    ],
  },
  {
    il: "Bolu",
    kod: 14,
    bolge: "Karadeniz",
    ilceler: [
      "Dörtdivan",
      "Gerede",
      "Göynük",
      "Kıbrıscık",
      "Mengen",
      "Merkez",
      "Mudurnu",
      "Seben",
      "Yeniçağa"
    ],
  },
  {
    il: "Burdur",
    kod: 15,
    bolge: "Akdeniz",
    ilceler: [
      "Ağlasun",
      "Altınyayla",
      "Bucak",
      "Çavdır",
      "Çeltikçi",
      "Gölhisar",
      "Karamanlı",
      "Kemer",
      "Merkez",
      "Tefenni",
      "Yeşilova"
    ],
  },
  {
    il: "Bursa",
    kod: 16,
    bolge: "Marmara",
    ilceler: [
      "Büyükorhan",
      "Gemlik",
      "Gürsu",
      "Harmancık",
      "İnegöl",
      "İznik",
      "Karacabey",
      "Keles",
      "Kestel",
      "Mudanya",
      "Mustafakemalpaşa",
      "Nilüfer",
      "Orhaneli",
      "Orhangazi",
      "Osmangazi",
      "Yenişehir",
      "Yıldırım"
    ],
  },
  {
    il: "Çanakkale",
    kod: 17,
    bolge: "Marmara",
    ilceler: [
      "Ayvacık",
      "Bayramiç",
      "Biga",
      "Bozcaada",
      "Çan",
      "Eceabat",
      "Ezine",
      "Gelibolu",
      "Gökçeada",
      "Lapseki",
      "Merkez",
      "Yenice"
    ],
  },
  {
    il: "Çankırı",
    kod: 18,
    bolge: "Marmara",
    ilceler: [
      "Atkaracalar",
      "Bayramören",
      "Çerkeş",
      "Eldivan",
      "Ilgaz",
      "Kızılırmak",
      "Korgun",
      "Kurşunlu",
      "Merkez",
      "Orta",
      "Şabanözü",
      "Yapraklı"
    ],
  },
  {
    il: "Çorum",
    kod: 19,
    bolge: "Karadeniz",
    ilceler: [
      "Alaca",
      "Bayat",
      "Boğazkale",
      "Dodurga",
      "İskilip",
      "Kargı",
      "Laçin",
      "Mecitözü",
      "Merkez",
      "Oğuzlar",
      "Ortaköy",
      "Osmancık",
      "Sungurlu",
      "Uğurludağ"
    ],
  },
  {
    il: "Denizli",
    kod: 20,
    bolge: "Ege",
    ilceler: [
      "Acıpayam",
      "Babadağ",
      "Baklan",
      "Bekilli",
      "Beyağaç",
      "Bozkurt",
      "Buldan",
      "Çal",
      "Çameli",
      "Çardak",
      "Çivril",
      "Güney",
      "Honaz",
      "Kale",
      "Merkezefendi",
      "Pamukkale",
      "Sarayköy",
      "Serinhisar",
      "Tavas"
    ],
  },
  {
    il: "Diyarbakır",
    kod: 21,
    bolge: "Güneydoğu Anadolu",
    ilceler: [
      "Bağlar",
      "Bismil",
      "Çermik",
      "Çınar",
      "Çüngüş",
      "Dicle",
      "Eğil",
      "Ergani",
      "Hani",
      "Hazro",
      "Kayapınar",
      "Kocaköy",
      "Kulp",
      "Lice",
      "Silvan",
      "Sur",
      "Yenişehir"
    ],
  },
  {
    il: "Edirne",
    kod: 22,
    bolge: "Marmara",
    ilceler: [
      "Enez",
      "Havsa",
      "İpsala",
      "Keşan",
      "Lalapaşa",
      "Meriç",
      "Merkez",
      "Süloğlu",
      "Uzunköprü"
    ],
  },
  {
    il: "Elazığ",
    kod: 23,
    bolge: "Doğu Anadolu",
    ilceler: [
      "Ağın",
      "Alacakaya",
      "Arıcak",
      "Baskil",
      "Karakoçan",
      "Keban",
      "Kovancılar",
      "Maden",
      "Merkez",
      "Palu",
      "Sivrice"
    ],
  },
  {
    il: "Erzincan",
    kod: 24,
    bolge: "Doğu Anadolu",
    ilceler: [
      "Çayırlı",
      "İliç",
      "Kemah",
      "Kemaliye",
      "Merkez",
      "Otlukbeli",
      "Refahiye",
      "Tercan",
      "Üzümlü"
    ],
  },
  {
    il: "Erzurum",
    kod: 25,
    bolge: "Doğu Anadolu",
    ilceler: [
      "Aşkale",
      "Aziziye",
      "Çat",
      "Hınıs",
      "Horasan",
      "İspir",
      "Karaçoban",
      "Karayazı",
      "Köprüköy",
      "Narman",
      "Oltu",
      "Olur",
      "Palandöken",
      "Pasinler",
      "Pazaryolu",
      "Şenkaya",
      "Tekman",
      "Tortum",
      "Uzundere",
      "Yakutiye"
    ],
  },
  {
    il: "Eskişehir",
    kod: 26,
    bolge: "İç Anadolu",
    ilceler: [
      "Alpu",
      "Beylikova",
      "Çifteler",
      "Günyüzü",
      "Han",
      "İnönü",
      "Mahmudiye",
      "Mihalgazi",
      "Mihalıççık",
      "Odunpazarı",
      "Sarıcakaya",
      "Seyitgazi",
      "Sivrihisar",
      "Tepebaşı"
    ],
  },
  {
    il: "Gaziantep",
    kod: 27,
    bolge: "Güneydoğu Anadolu",
    ilceler: [
      "Araban",
      "İslahiye",
      "Karkamış",
      "Nizip",
      "Nurdağı",
      "Oğuzeli",
      "Şahinbey",
      "Şehitkamil",
      "Yavuzeli"
    ],
  },
  {
    il: "Giresun",
    kod: 28,
    bolge: "Karadeniz",
    ilceler: [
      "Alucra",
      "Bulancak",
      "Çamoluk",
      "Çanakçı",
      "Dereli",
      "Doğankent",
      "Espiye",
      "Eynesil",
      "Görele",
      "Güce",
      "Keşap",
      "Merkez",
      "Piraziz",
      "Şebinkarahisar",
      "Tirebolu",
      "Yağlıdere"
    ],
  },
  {
    il: "Gümüşhane",
    kod: 29,
    bolge: "Karadeniz",
    ilceler: [
      "Kelkit",
      "Köse",
      "Kürtün",
      "Merkez",
      "Şiran",
      "Torul"
    ],
  },
  {
    il: "Hakkari",
    kod: 30,
    bolge: "Güneydoğu Anadolu",
    ilceler: [
      "Çukurca",
      "Derecik",
      "Merkez",
      "Şemdinli",
      "Yüksekova"
    ],
  },
  {
    il: "Hatay",
    kod: 31,
    bolge: "Akdeniz",
    ilceler: [
      "Altınözü",
      "Antakya",
      "Arsuz",
      "Belen",
      "Defne",
      "Dörtyol",
      "Erzin",
      "Hassa",
      "İskenderun",
      "Kırıkhan",
      "Kumlu",
      "Payas",
      "Reyhanlı",
      "Samandağ",
      "Yayladağı"
    ],
  },
  {
    il: "Isparta",
    kod: 32,
    bolge: "Akdeniz",
    ilceler: [
      "Aksu",
      "Atabey",
      "Eğirdir",
      "Gelendost",
      "Gönen",
      "Keçiborlu",
      "Merkez",
      "Senirkent",
      "Sütçüler",
      "Şarkikaraağaç",
      "Uluborlu",
      "Yalvaç",
      "Yenişarbademli"
    ],
  },
  {
    il: "Mersin",
    kod: 33,
    bolge: "Akdeniz",
    ilceler: [
      "Akdeniz",
      "Anamur",
      "Aydıncık",
      "Bozyazı",
      "Çamlıyayla",
      "Erdemli",
      "Gülnar",
      "Mezitli",
      "Mut",
      "Silifke",
      "Tarsus",
      "Toroslar",
      "Yenişehir"
    ],
  },
  {
    il: "İstanbul",
    kod: 34,
    bolge: "Marmara",
    ilceler: [
      "Adalar",
      "Arnavutköy",
      "Ataşehir",
      "Avcılar",
      "Bağcılar",
      "Bahçelievler",
      "Bakırköy",
      "Başakşehir",
      "Bayrampaşa",
      "Beşiktaş",
      "Beykoz",
      "Beylikdüzü",
      "Beyoğlu",
      "Büyükçekmece",
      "Çatalca",
      "Çekmeköy",
      "Esenler",
      "Esenyurt",
      "Eyüpsultan",
      "Fatih",
      "Gaziosmanpaşa",
      "Güngören",
      "Kadıköy",
      "Kağıthane",
      "Kartal",
      "Küçükçekmece",
      "Maltepe",
      "Pendik",
      "Sancaktepe",
      "Sarıyer",
      "Silivri",
      "Sultanbeyli",
      "Sultangazi",
      "Şile",
      "Şişli",
      "Tuzla",
      "Ümraniye",
      "Üsküdar",
      "Zeytinburnu"
    ],
  },
  {
    il: "İzmir",
    kod: 35,
    bolge: "Ege",
    ilceler: [
      "Aliağa",
      "Balçova",
      "Bayındır",
      "Bayraklı",
      "Bergama",
      "Beydağ",
      "Bornova",
      "Buca",
      "Çeşme",
      "Çiğli",
      "Dikili",
      "Foça",
      "Gaziemir",
      "Güzelbahçe",
      "Karabağlar",
      "Karaburun",
      "Karşıyaka",
      "Kemalpaşa",
      "Kınık",
      "Kiraz",
      "Konak",
      "Menderes",
      "Menemen",
      "Narlıdere",
      "Ödemiş",
      "Seferihisar",
      "Selçuk",
      "Tire",
      "Torbalı",
      "Urla"
    ],
  },
  {
    il: "Kars",
    kod: 36,
    bolge: "Doğu Anadolu",
    ilceler: [
      "Akyaka",
      "Arpaçay",
      "Digor",
      "Kağızman",
      "Merkez",
      "Sarıkamış",
      "Selim",
      "Susuz"
    ],
  },
  {
    il: "Kastamonu",
    kod: 37,
    bolge: "Karadeniz",
    ilceler: [
      "Abana",
      "Ağlı",
      "Araç",
      "Azdavay",
      "Bozkurt",
      "Cide",
      "Çatalzeytin",
      "Daday",
      "Devrekani",
      "Doğanyurt",
      "Hanönü",
      "İhsangazi",
      "İnebolu",
      "Küre",
      "Merkez",
      "Pınarbaşı",
      "Seydiler",
      "Şenpazar",
      "Taşköprü",
      "Tosya"
    ],
  },
  {
    il: "Kayseri",
    kod: 38,
    bolge: "İç Anadolu",
    ilceler: [
      "Akkışla",
      "Bünyan",
      "Develi",
      "Felahiye",
      "Hacılar",
      "İncesu",
      "Kocasinan",
      "Melikgazi",
      "Özvatan",
      "Pınarbaşı",
      "Sarıoğlan",
      "Sarız",
      "Talas",
      "Tomarza",
      "Yahyalı",
      "Yeşilhisar"
    ],
  },
  {
    il: "Kırklareli",
    kod: 39,
    bolge: "Marmara",
    ilceler: [
      "Babaeski",
      "Demirköy",
      "Kofçaz",
      "Lüleburgaz",
      "Merkez",
      "Pehlivanköy",
      "Pınarhisar",
      "Vize"
    ],
  },
  {
    il: "Kırşehir",
    kod: 40,
    bolge: "İç Anadolu",
    ilceler: [
      "Akçakent",
      "Akpınar",
      "Boztepe",
      "Çiçekdağı",
      "Kaman",
      "Merkez",
      "Mucur"
    ],
  },
  {
    il: "Kocaeli",
    kod: 41,
    bolge: "Marmara",
    ilceler: [
      "Başiskele",
      "Çayırova",
      "Darıca",
      "Derince",
      "Dilovası",
      "Gebze",
      "Gölcük",
      "İzmit",
      "Kandıra",
      "Karamürsel",
      "Kartepe",
      "Körfez"
    ],
  },
  {
    il: "Konya",
    kod: 42,
    bolge: "İç Anadolu",
    ilceler: [
      "Ahırlı",
      "Akören",
      "Akşehir",
      "Altınekin",
      "Beyşehir",
      "Bozkır",
      "Cihanbeyli",
      "Çeltik",
      "Çumra",
      "Derbent",
      "Derebucak",
      "Doğanhisar",
      "Emirgazi",
      "Ereğli",
      "Güneysınır",
      "Hadim",
      "Halkapınar",
      "Hüyük",
      "Ilgın",
      "Kadınhanı",
      "Karapınar",
      "Karatay",
      "Kulu",
      "Meram",
      "Sarayönü",
      "Selçuklu",
      "Seydişehir",
      "Taşkent",
      "Tuzlukçu",
      "Yalıhüyük",
      "Yunak"
    ],
  },
  {
    il: "Kütahya",
    kod: 43,
    bolge: "Ege",
    ilceler: [
      "Altıntaş",
      "Aslanapa",
      "Çavdarhisar",
      "Domaniç",
      "Dumlupınar",
      "Emet",
      "Gediz",
      "Hisarcık",
      "Merkez",
      "Pazarlar",
      "Simav",
      "Şaphane",
      "Tavşanlı"
    ],
  },
  {
    il: "Malatya",
    kod: 44,
    bolge: "Doğu Anadolu",
    ilceler: [
      "Akçadağ",
      "Arapgir",
      "Arguvan",
      "Battalgazi",
      "Darende",
      "Doğanşehir",
      "Doğanyol",
      "Hekimhan",
      "Kale",
      "Kuluncak",
      "Pütürge",
      "Yazıhan",
      "Yeşilyurt"
    ],
  },
  {
    il: "Manisa",
    kod: 45,
    bolge: "Ege",
    ilceler: [
      "Ahmetli",
      "Akhisar",
      "Alaşehir",
      "Demirci",
      "Gölmarmara",
      "Gördes",
      "Kırkağaç",
      "Köprübaşı",
      "Kula",
      "Salihli",
      "Sarıgöl",
      "Saruhanlı",
      "Selendi",
      "Soma",
      "Şehzadeler",
      "Turgutlu",
      "Yunusemre"
    ],
  },
  {
    il: "Kahramanmaraş",
    kod: 46,
    bolge: "Akdeniz",
    ilceler: [
      "Afşin",
      "Andırın",
      "Çağlayancerit",
      "Dulkadiroğlu",
      "Ekinözü",
      "Elbistan",
      "Göksun",
      "Nurhak",
      "Onikişubat",
      "Pazarcık",
      "Türkoğlu"
    ],
  },
  {
    il: "Mardin",
    kod: 47,
    bolge: "Güneydoğu Anadolu",
    ilceler: [
      "Artuklu",
      "Dargeçit",
      "Derik",
      "Kızıltepe",
      "Mazıdağı",
      "Midyat",
      "Nusaybin",
      "Ömerli",
      "Savur",
      "Yeşilli"
    ],
  },
  {
    il: "Muğla",
    kod: 48,
    bolge: "Ege",
    ilceler: [
      "Bodrum",
      "Dalaman",
      "Datça",
      "Fethiye",
      "Kavaklıdere",
      "Köyceğiz",
      "Marmaris",
      "Menteşe",
      "Milas",
      "Ortaca",
      "Seydikemer",
      "Ula",
      "Yatağan"
    ],
  },
  {
    il: "Muş",
    kod: 49,
    bolge: "Doğu Anadolu",
    ilceler: [
      "Bulanık",
      "Hasköy",
      "Korkut",
      "Malazgirt",
      "Merkez",
      "Varto"
    ],
  },
  {
    il: "Nevşehir",
    kod: 50,
    bolge: "İç Anadolu",
    ilceler: [
      "Acıgöl",
      "Avanos",
      "Derinkuyu",
      "Gülşehir",
      "Hacıbektaş",
      "Kozaklı",
      "Merkez",
      "Ürgüp"
    ],
  },
  {
    il: "Niğde",
    kod: 51,
    bolge: "İç Anadolu",
    ilceler: [
      "Altunhisar",
      "Bor",
      "Çamardı",
      "Çiftlik",
      "Merkez",
      "Ulukışla"
    ],
  },
  {
    il: "Ordu",
    kod: 52,
    bolge: "Karadeniz",
    ilceler: [
      "Akkuş",
      "Altınordu",
      "Aybastı",
      "Çamaş",
      "Çatalpınar",
      "Çaybaşı",
      "Fatsa",
      "Gölköy",
      "Gülyalı",
      "Gürgentepe",
      "İkizce",
      "Kabadüz",
      "Kabataş",
      "Korgan",
      "Kumru",
      "Mesudiye",
      "Perşembe",
      "Ulubey",
      "Ünye"
    ],
  },
  {
    il: "Rize",
    kod: 53,
    bolge: "Karadeniz",
    ilceler: [
      "Ardeşen",
      "Çamlıhemşin",
      "Çayeli",
      "Derepazarı",
      "Fındıklı",
      "Güneysu",
      "Hemşin",
      "İkizdere",
      "İyidere",
      "Kalkandere",
      "Merkez",
      "Pazar"
    ],
  },
  {
    il: "Sakarya",
    kod: 54,
    bolge: "Marmara",
    ilceler: [
      "Adapazarı",
      "Akyazı",
      "Arifiye",
      "Erenler",
      "Ferizli",
      "Geyve",
      "Hendek",
      "Karapürçek",
      "Karasu",
      "Kaynarca",
      "Kocaali",
      "Pamukova",
      "Sapanca",
      "Serdivan",
      "Söğütlü",
      "Taraklı"
    ],
  },
  {
    il: "Samsun",
    kod: 55,
    bolge: "Karadeniz",
    ilceler: [
      "19 Mayıs",
      "Alaçam",
      "Asarcık",
      "Atakum",
      "Ayvacık",
      "Bafra",
      "Canik",
      "Çarşamba",
      "Havza",
      "İlkadım",
      "Kavak",
      "Ladik",
      "Salıpazarı",
      "Tekkeköy",
      "Terme",
      "Vezirköprü",
      "Yakakent"
    ],
  },
  {
    il: "Siirt",
    kod: 56,
    bolge: "Güneydoğu Anadolu",
    ilceler: [
      "Baykan",
      "Eruh",
      "Kurtalan",
      "Merkez",
      "Pervari",
      "Şirvan",
      "Tillo"
    ],
  },
  {
    il: "Sinop",
    kod: 57,
    bolge: "Karadeniz",
    ilceler: [
      "Ayancık",
      "Boyabat",
      "Dikmen",
      "Durağan",
      "Erfelek",
      "Gerze",
      "Merkez",
      "Saraydüzü",
      "Türkeli"
    ],
  },
  {
    il: "Sivas",
    kod: 58,
    bolge: "İç Anadolu",
    ilceler: [
      "Akıncılar",
      "Altınyayla",
      "Divriği",
      "Doğanşar",
      "Gemerek",
      "Gölova",
      "Gürün",
      "Hafik",
      "İmranlı",
      "Kangal",
      "Koyulhisar",
      "Merkez",
      "Suşehri",
      "Şarkışla",
      "Ulaş",
      "Yıldızeli",
      "Zara"
    ],
  },
  {
    il: "Tekirdağ",
    kod: 59,
    bolge: "Marmara",
    ilceler: [
      "Çerkezköy",
      "Çorlu",
      "Ergene",
      "Hayrabolu",
      "Kapaklı",
      "Malkara",
      "Marmaraereğlisi",
      "Muratlı",
      "Saray",
      "Süleymanpaşa",
      "Şarköy"
    ],
  },
  {
    il: "Tokat",
    kod: 60,
    bolge: "Karadeniz",
    ilceler: [
      "Almus",
      "Artova",
      "Başçiftlik",
      "Erbaa",
      "Merkez",
      "Niksar",
      "Pazar",
      "Reşadiye",
      "Sulusaray",
      "Turhal",
      "Yeşilyurt",
      "Zile"
    ],
  },
  {
    il: "Trabzon",
    kod: 61,
    bolge: "Karadeniz",
    ilceler: [
      "Akçaabat",
      "Araklı",
      "Arsin",
      "Beşikdüzü",
      "Çarşıbaşı",
      "Çaykara",
      "Dernekpazarı",
      "Düzköy",
      "Hayrat",
      "Köprübaşı",
      "Maçka",
      "Of",
      "Ortahisar",
      "Sürmene",
      "Şalpazarı",
      "Tonya",
      "Vakfıkebir",
      "Yomra"
    ],
  },
  {
    il: "Tunceli",
    kod: 62,
    bolge: "Doğu Anadolu",
    ilceler: [
      "Çemişgezek",
      "Hozat",
      "Mazgirt",
      "Merkez",
      "Nazımiye",
      "Ovacık",
      "Pertek",
      "Pülümür"
    ],
  },
  {
    il: "Şanlıurfa",
    kod: 63,
    bolge: "Güneydoğu Anadolu",
    ilceler: [
      "Akçakale",
      "Birecik",
      "Bozova",
      "Ceylanpınar",
      "Eyyübiye",
      "Halfeti",
      "Haliliye",
      "Harran",
      "Hilvan",
      "Karaköprü",
      "Siverek",
      "Suruç",
      "Viranşehir"
    ],
  },
  {
    il: "Uşak",
    kod: 64,
    bolge: "Ege",
    ilceler: [
      "Banaz",
      "Eşme",
      "Karahallı",
      "Merkez",
      "Sivaslı",
      "Ulubey"
    ],
  },
  {
    il: "Van",
    kod: 65,
    bolge: "Doğu Anadolu",
    ilceler: [
      "Bahçesaray",
      "Başkale",
      "Çaldıran",
      "Çatak",
      "Edremit",
      "Erciş",
      "Gevaş",
      "Gürpınar",
      "İpekyolu",
      "Muradiye",
      "Özalp",
      "Saray",
      "Tuşba"
    ],
  },
  {
    il: "Yozgat",
    kod: 66,
    bolge: "İç Anadolu",
    ilceler: [
      "Akdağmadeni",
      "Aydıncık",
      "Boğazlıyan",
      "Çandır",
      "Çayıralan",
      "Çekerek",
      "Kadışehri",
      "Merkez",
      "Saraykent",
      "Sarıkaya",
      "Sorgun",
      "Şefaatli",
      "Yenifakılı",
      "Yerköy"
    ],
  },
  {
    il: "Zonguldak",
    kod: 67,
    bolge: "Karadeniz",
    ilceler: [
      "Alaplı",
      "Çaycuma",
      "Devrek",
      "Ereğli",
      "Gökçebey",
      "Kilimli",
      "Kozlu",
      "Merkez"
    ],
  },
  {
    il: "Aksaray",
    kod: 68,
    bolge: "İç Anadolu",
    ilceler: [
      "Ağaçören",
      "Eskil",
      "Gülağaç",
      "Güzelyurt",
      "Merkez",
      "Ortaköy",
      "Sarıyahşi",
      "Sultanhanı"
    ],
  },
  {
    il: "Bayburt",
    kod: 69,
    bolge: "Karadeniz",
    ilceler: [
      "Aydıntepe",
      "Demirözü",
      "Merkez"
    ],
  },
  {
    il: "Karaman",
    kod: 70,
    bolge: "İç Anadolu",
    ilceler: [
      "Ayrancı",
      "Başyayla",
      "Ermenek",
      "Kazımkarabekir",
      "Merkez",
      "Sarıveliler"
    ],
  },
  {
    il: "Kırıkkale",
    kod: 71,
    bolge: "İç Anadolu",
    ilceler: [
      "Bahşılı",
      "Balışeyh",
      "Çelebi",
      "Delice",
      "Karakeçili",
      "Keskin",
      "Merkez",
      "Sulakyurt",
      "Yahşihan"
    ],
  },
  {
    il: "Batman",
    kod: 72,
    bolge: "Güneydoğu Anadolu",
    ilceler: [
      "Beşiri",
      "Gercüş",
      "Hasankeyf",
      "Kozluk",
      "Merkez",
      "Sason"
    ],
  },
  {
    il: "Şırnak",
    kod: 73,
    bolge: "Güneydoğu Anadolu",
    ilceler: [
      "Beytüşşebap",
      "Cizre",
      "Güçlükonak",
      "İdil",
      "Merkez",
      "Silopi",
      "Uludere"
    ],
  },
  {
    il: "Bartın",
    kod: 74,
    bolge: "Karadeniz",
    ilceler: [
      "Amasra",
      "Kurucaşile",
      "Merkez",
      "Ulus"
    ],
  },
  {
    il: "Ardahan",
    kod: 75,
    bolge: "Doğu Anadolu",
    ilceler: [
      "Çıldır",
      "Damal",
      "Göle",
      "Hanak",
      "Merkez",
      "Posof"
    ],
  },
  {
    il: "Iğdır",
    kod: 76,
    bolge: "Doğu Anadolu",
    ilceler: [
      "Aralık",
      "Karakoyunlu",
      "Merkez",
      "Tuzluca"
    ],
  },
  {
    il: "Yalova",
    kod: 77,
    bolge: "Marmara",
    ilceler: [
      "Altınova",
      "Armutlu",
      "Çınarcık",
      "Çiftlikköy",
      "Merkez",
      "Termal"
    ],
  },
  {
    il: "Karabük",
    kod: 78,
    bolge: "Karadeniz",
    ilceler: [
      "Eflani",
      "Eskipazar",
      "Merkez",
      "Ovacık",
      "Safranbolu",
      "Yenice"
    ],
  },
  {
    il: "Kilis",
    kod: 79,
    bolge: "Güneydoğu Anadolu",
    ilceler: [
      "Elbeyli",
      "Merkez",
      "Musabeyli",
      "Polateli"
    ],
  },
  {
    il: "Osmaniye",
    kod: 80,
    bolge: "Akdeniz",
    ilceler: [
      "Bahçe",
      "Düziçi",
      "Hasanbeyli",
      "Kadirli",
      "Merkez",
      "Sumbas",
      "Toprakkale"
    ],
  },
  {
    il: "Düzce",
    kod: 81,
    bolge: "Karadeniz",
    ilceler: [
      "Akçakoca",
      "Cumayeri",
      "Çilimli",
      "Gölyaka",
      "Gümüşova",
      "Kaynaşlı",
      "Merkez",
      "Yığılca"
    ],
  },
];
